export default {
  'png': 'image',
  'jpg': 'image',
  'jpeg': 'image',
  'gif': 'image',
  'bmp': 'image',
  'tiff': 'image',
  'mp4': 'video',
  'mov': 'video',
  'avi': 'video',
  'mp3': 'audio',
  'aac': 'audio',
  'md': 'markdown',
  'html': 'document',
  'cf': 'document',
  'conf': 'document',
  'config': 'document',
  'nfo': 'document',
  'txt': 'document',
  'defaultType': 'default-type'
};
